[package]
name = "kp-chart"
version = "0.1.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

[lib]
name = "kp_chart"
path = "src/lib.rs"

[[bin]]
name = "kp-chart"
path = "src/main.rs"

[features]
default = ["web-spa"]
web-spa = ["yew"]

[dependencies]
yew = {version = "0.4.0", optional = true}